// Default border and highlighted cage styling. Syntax: one space between each value and multi-value attributes (e.g., rgba) may not contain any spaces
const BORDER_DEFAULT = '0 0 0 1px black';
const BORDER_HIGHLIGHT = 'inset 0 0 0 3px rgba(0,0,0,0.8)';

// Key: puzzle size, value: weights for size 2, 3, and 4 cages
const CAGE_SIZE_WEIGHTS = {
	4: [6, 3, 1],
	5: [6, 3, 1],
	6: [4, 3, 3],
	7: [4, 3, 3],
	8: [2, 4, 4],
	9: [2, 4, 4],
};

const CSS_COLOR_NAMES = [
	'AliceBlue',
	'AntiqueWhite',
	// 'Aqua',
	'Aquamarine',
	'Azure',
	'Beige',
	// 'Bisque',
	// 'Black',
	'BlanchedAlmond',
	// 'Blue',
	// 'BlueViolet',
	// 'Brown',
	'BurlyWood',
	// 'CadetBlue',
	// 'Chartreuse',
	// 'Chocolate',
	// 'Coral',
	// 'CornflowerBlue',
	'Cornsilk',
	// 'Crimson',
	'Cyan',
	// 'DarkBlue',
	// 'DarkCyan',
	// 'DarkGoldenRod',
	// 'DarkGray',
	// 'DarkGrey',
	// 'DarkGreen',
	// 'DarkKhaki',
	// 'DarkMagenta',
	// 'DarkOliveGreen',
	// 'DarkOrange',
	// 'DarkOrchid',
	// 'DarkRed',
	// 'DarkSalmon',
	// 'DarkSeaGreen',
	// 'DarkSlateBlue',
	// 'DarkSlateGray',
	// 'DarkSlateGrey',
	// 'DarkTurquoise',
	// 'DarkViolet',
	// 'DeepPink',
	// 'DeepSkyBlue',
	// 'DimGray',
	// 'DimGrey',
	// 'DodgerBlue',
	// 'FireBrick',
	'FloralWhite',
	// 'ForestGreen',
	// 'Fuchsia',
	'Gainsboro',
	// 'GhostWhite',
	// 'Gold',
	'GoldenRod',
	// 'Gray',
	// 'Grey',
	// 'Green',
	// 'GreenYellow',
	'HoneyDew',
	'HotPink',
	// 'IndianRed',
	// 'Indigo',
	// 'Ivory',
	'Khaki',
	'Lavender',
	'LavenderBlush',
	// 'LawnGreen',
	'LemonChiffon',
	'LightBlue',
	'LightCoral',
	'LightCyan',
	// 'LightGoldenRodYellow',
	'LightGray',
	// 'LightGrey',
	'LightGreen',
	// 'LightPink',
	'LightSalmon',
	// 'LightSeaGreen',
	'LightSkyBlue',
	// 'LightSlateGray',
	// 'LightSlateGrey',
	'LightSteelBlue',
	'LightYellow',
	// 'Lime',
	'LimeGreen',
	'Linen',
	// 'Magenta',
	// 'Maroon',
	'MediumAquaMarine',
	// 'MediumBlue',
	// 'MediumOrchid',
	// 'MediumPurple',
	'MediumSeaGreen',
	// 'MediumSlateBlue',
	'MediumSpringGreen',
	'MediumTurquoise',
	// 'MediumVioletRed',
	// 'MidnightBlue',
	'MintCream',
	'MistyRose',
	'Moccasin',
	'NavajoWhite',
	// 'Navy',
	// 'OldLace',
	// 'Olive',
	// 'OliveDrab',
	// 'Orange',
	// 'OrangeRed',
	'Orchid',
	'PaleGoldenRod',
	'PaleGreen',
	'PaleTurquoise',
	// 'PaleVioletRed',
	// 'PapayaWhip',
	'PeachPuff',
	'Peru',
	'Pink',
	'Plum',
	'PowderBlue',
	// 'Purple',
	// 'RebeccaPurple',
	// 'Red',
	'RosyBrown',
	// 'RoyalBlue',
	// 'SaddleBrown',
	'Salmon',
	// 'SandyBrown',
	// 'SeaGreen',
	'SeaShell',
	// 'Sienna',
	'Silver',
	'SkyBlue',
	// 'SlateBlue',
	// 'SlateGray',
	// 'SlateGrey',
	'Snow',
	'SpringGreen',
	// 'SteelBlue',
	'Tan',
	// 'Teal',
	'Thistle',
	// 'Tomato',
	'Turquoise',
	'Violet',
	'Wheat',
	// 'White',
	// 'WhiteSmoke',
	// 'Yellow',
	// 'YellowGreen',
];

export { BORDER_DEFAULT, BORDER_HIGHLIGHT, CAGE_SIZE_WEIGHTS, CSS_COLOR_NAMES };
